### ISSUE TITLE
Reusable interface

### ISSUE THREAD

**Issue by chapulina** [osrf/gz-grant#1]
Currently gz-grant sends GET requests on `/grant` and `/revoke`, which [works](https://bitbucket.org/osrf/cloudsim-sim/src/e2b2916d0db036f6953c4ecce84906dba47a685d/server/server.js?at=default&fileviewer=file-view-default#server.js-243) with `cloudsim-sim`, but not with `cloudsim-portal`. It would be nice to have a unified interface so gz-grant can talk to both servers.

As a reference, `cloudsim-portal` expects [POST](https://bitbucket.org/osrf/cloudsim-portal/src/443cc92c36a3e6ba3dff66c79b6375ce802db5db/test/mocha/simulator/controller.js?at=default&fileviewer=file-view-default#controller.js-283) and [DELETE](https://bitbucket.org/osrf/cloudsim-portal/src/443cc92c36a3e6ba3dff66c79b6375ce802db5db/test/mocha/simulator/controller.js?at=default&fileviewer=file-view-default#controller.js-513) to `/simulators/permissions`.

**Comment by chapulina** [comment]
@hugomatic @iche033

**Comment by hugomatic** [comment]
What we decided:
- use /permissions
- use POST and DELETE, and put all info into the body (not params)

update cloudsim-sim, cloudsim-grant and cloudsim-portal.

**Comment by chapulina** [comment]
[cloudsim-portal pull request](https://bitbucket.org/osrf/cloudsim-portal/pull-requests/6/permissions-instead-of-simulators/diff)

**Comment by chapulina** [comment]
pull request #2
